<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="cty" ignored="0" name="Default test" tests="2" failures="1" timestamp="10 五月 2018 05:54:41 GMT" time="4.242" errors="0">
  <testcase name="testFailed" time="2.161" classname="pri.study.timeout.Timeout">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method pri.study.timeout.Timeout.testFailed() didn&amp;apos;t finish within the time-out 2000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method pri.study.timeout.Timeout.testFailed() didn't finish within the time-out 2000
]]>
    </failure>
  </testcase> <!-- testFailed -->
  <testcase name="testSuccess" time="2.004" classname="pri.study.timeout.Timeout"/>
</testsuite> <!-- Default test -->
