<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="cty" name="pri.study.timeout.Timeout" tests="2" failures="0" timestamp="10 五月 2018 05:54:41 GMT" time="4.165" errors="1">
  <testcase name="testSuccess" time="2.004" classname="pri.study.timeout.Timeout"/>
  <testcase name="testFailed" time="2.161" classname="pri.study.timeout.Timeout">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method pri.study.timeout.Timeout.testFailed() didn&#039;t finish within the time-out 2000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method pri.study.timeout.Timeout.testFailed() didn't finish within the time-out 2000
]]>
    </error>
  </testcase> <!-- testFailed -->
</testsuite> <!-- pri.study.timeout.Timeout -->
